### ISSUE TITLE
Any dataset release plan ?  thanks! 

### ISSUE THREAD

**Issue by sanbuphy** [cosmicman-cvpr2024/CosmicMan#4]
great work ! i want to ask if we can get the inference code or dataset recently

**Comment by akk-123** [comment]
+1

**Comment by xinli2008** [comment]
+1

**Comment by wywu** [comment]
https://huggingface.co/datasets/cosmicman/CosmicManHQ-1.0

Thank you for waiting.

**Comment by zhou431496** [comment]
> great work ! i want to ask if we can get the inference code or dataset recently
您好，如何从数据集中获取图像的文本描述
