### ISSUE TITLE
An error about AspectBucket

### ISSUE THREAD

**Issue by ChaoFan996** [cosmicman-cvpr2024/CosmicMan#7]
Hi, thanks for your excellent work! 
I have tried to train the model but met an error: 
`
[rank4]:     self.init_buckets()
[rank4]:   File "./CosmicMan/dataset.py", line 334, in init_buckets
[rank4]:     self._bucket_interp = interp1d(self._bucket_ratios, list(range(len(buckets))), assume_sorted=True,
[rank4]:   File "/root/miniconda/envs/cosmicman/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 543, in __init__
[rank4]:     self._y = self._reshape_yi(self.y)
[rank4]:   File "/root/miniconda/envs/cosmicman/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 113, in _reshape_yi
[rank4]:     return yi.reshape((yi.shape[0], -1))
`
It seems that the self.buckets has been wrongly set to an empty list. 
Would you provide any suggestions to address this issue? 
Thanks!

**Comment by ChaoFan996** [comment]
I may fix this bug. 
The arg name in [this line](https://github.com/cosmicman-cvpr2024/CosmicMan/blob/483794759ba55adb2e17b479546422fb66d1febd/train_sdxl.sh#L27) should be `bucket_side_max` rather than `bucket_side_min`, right?

**Comment by leesky1c** [comment]
Yep! Thanks for the correction XD
